Update joining-a-testnet.md
fetchai/fetchd pull request #114
Opened 2021-06-24 15:02 UTC by jeremiegrr

2021-06-24 15:20 UTC, daeMOn63 requested changes
Looks good! Just a little section to revert, we'll still need it to keep every other commands simple

2021-06-24 15:20 UTC, daeMOn63 commented on docs/docs/joining-a-testnet.md
> -### Configuring the client `fetchcli`
we still need to configure the client, it's only renamed to  `fetchd` and dropped the `trust-node` config. 
So we can still set `chain-id` and `node`  options.

> Just FYI, some extra infos that don't really belong here, but we might want to have it on some other pages:


This config command avoid having to provide these flags on every other command
ie without config:
```
fetchd query staking validators --node https://rpc-stargateworld.fetch.ai:443 --chain-id stargateworld-1 
fetchd tx bank send account1 account2 1atestfet --node https://rpc-stargateworld.fetch.ai:443 --chain-id stargateworld-1
```
now with config:

```bash
fetchd config node https://rpc-stargateworld.fetch.ai:443
fetchd config chain-id stargateworld-1

# now the following will still work the same as above:

fetchd query staking validators 
fetchd tx bank send account1 account2 1atestfet 
```

And few extra bits:
```bash
fetchd config # display current config
cat ~/.fetchd/config/client.toml # this is the file where the config is written
```

2021-06-24 16:21 UTC, jeremiegrr reviewed
for review

2021-06-25 15:08 UTC, daeMOn63 requested changes

2021-06-25 15:08 UTC, daeMOn63 commented on docs/docs/joining-a-testnet.md
> +Assuming that you have following the [installation guide](../building/). You should now have `fetchd` successfully installed in your path. You can check this with the following command:
```suggestion
Assuming that you have followed the [installation guide](../building/). You should now have `fetchd` successfully installed in your path. You can check this with the following command:
```

2021-06-25 15:08 UTC, daeMOn63 commented on docs/docs/joining-a-testnet.md
> +# now the following will still work the same as above:
```suggestion
```

2021-06-25 15:08 UTC, daeMOn63 commented on docs/docs/joining-a-testnet.md
> +
```suggestion
```
This doesn't really belong to "joining a testnet", more on a general CLI usage document

2021-06-25 16:24 UTC, daeMOn63 commented
fixed and merged in #118

2021-06-25 16:24 UTC, closed without merging