Add multisig docs
fetchai/fetchd pull request #123
Opened 2021-07-02 16:06 UTC by Josumner

2021-07-02 18:11 UTC, ejfitzgerald requested changes
Really nice one @Josumner , just a couple of minor updates and we should get this merged

2021-07-02 18:11 UTC, ejfitzgerald commented on docs/mkdocs.yml
> +strict: false
```suggestion
strict: true
```

Lets restore this back to the original

2021-07-02 18:11 UTC, ejfitzgerald commented on docs/docs/cli-multisig.md
> +Documentation describing the creation of multisig keys and signing transactions.
```suggestion
```

I think that we simply remove this line

2021-07-03 08:14 UTC, daeMOn63 commented on docs/docs/cli-multisig.md
> +// Create a simple multisig key with a threshold of 1 as default
```suggestion
# Create a simple multisig key with a threshold of 1 as default
```
an extra nit: comments in bash are with a `#`, not `//`

2021-07-06 09:27 UTC, ejfitzgerald approved these changes
Nice one!

2021-07-06 12:59 UTC, merged