docs: updated network information
fetchai/fetchd pull request #180
Opened 2022-01-06 13:50 UTC by jonathan6620

2022-01-12 13:38 UTC, ejfitzgerald submitted a review, later dismissed

2022-01-12 14:31 UTC, daeMOn63 requested changes
Capricorn infos will need to change (at least the release version) and we'll need to add some seeds too. But thanks, I'll update & deploy it when we'll be set!

2022-02-02 10:44 UTC, ejfitzgerald approved these changes

2022-02-02 10:47 UTC, daeMOn63 approved these changes

2022-02-02 10:48 UTC, merged